services:
  frontend:
    build:
        context: .
        dockerfile: "Dockerfile.next"

    ports: 
      - "3000:3000"
  
  backend:
    build:
        context: .
        dockerfile: "Dockerfile.python"

    ports: 
      - "8000:8000"

